name: NDQ_Analysis_Auto_Update

on:
  schedule:
    # 1. 장 마감 1시간 뒤 (현지 오후 5시 / UTC 21:00) -> 1차 기록
    - cron: '0 21 * * *'
    
    # 2. 다음 날 장 시작 30분 전 (현지 오전 10시 / UTC 14:00) -> 최종 데이터 확정 및 업데이트
    - cron: '0 13 * * *'
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install yfinance gspread pandas google-auth

      - name: Run NDQ Analysis
        env:
          # 여기서 'GOOGLE_SHEETS_JSON'이 깃허브 Secrets에 등록된 그 이름이어야 합니다!
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
        run: python "ndqanly.py"
